CREATE TABLE cash_sale (
	ID			INTEGER PRIMARY KEY,
	ProductID	INTEGER NOT NULL,
	SaleDate	TEXT,
	Discount	INTEGER NOT NULL,
);



CREATE TABLE product (
	ID 		INTEGER PRIMARY KEY,
	Name	TEXT	NOT NULL,
	CompanyID	INTEGER REFERENCES Company(ID),
	Price		TEXT	NOT NULL,
	ExpiryDate	TEXT	NOT NULL
);



CREATE TABLE stock (
	ProductId	INTEGER REFERENCES Product(ID),
	CompanyId	INTEGER	REFERENCES Company(ID),
	Quantity	INTEGER NOT NULL,
	ProductName	TEXT NOT NULL
);